CREATE TABLE Book_Details(
Book_ID SERIAL PRIMARY KEY,
Book_Name VARCHAR(60) NOT NULL,
Author_Name VARCHAR(30) NOT NULL,
Genre VARCHAR(60) NOT NULL,
Date_Published DATE,
No_of_Copies INT,
ISBN VARCHAR(15) UNIQUE NOT NULL,
Cost DECIMAL(10, 2)
);

CREATE TABLE Author_Details( 
Author_ID SERIAL PRIMARY KEY,
Book_ID SERIAL NOT NULL,
First_Name VARCHAR(30) NOT NULL,
Last_Name VARCHAR(30) NOT NULL,
FOREIGN KEY (Book_ID) REFERENCES Book_Details(Book_ID) ON DELETE CASCADE
);

CREATE TABLE Customer_Details(
Customer_ID SERIAL PRIMARY KEY,
First_Name VARCHAR(30) NOT NULL,
Last_Name VARCHAR(30) NOT NULL,
Email VARCHAR(30) UNIQUE NOT NULL,
Phone_No VARCHAR(20) UNIQUE NOT NULL,
Address VARCHAR(100)
);

CREATE TABLE Librarian_Details(  
Employee_ID SERIAL PRIMARY KEY,
First_Name VARCHAR(30) NOT NULL,
Last_Name VARCHAR(30) NOT NULL,
Phone_No VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE Book_Transaction_Details( 
Purchase_ID SERIAL PRIMARY KEY,
Book_ID SERIAL NOT NULL,
Customer_ID SERIAL NOT NULL,
Employee_ID SERIAL NOT NULL,
Issued_Date DATE,
Return_Date DATE,
Due_Date DATE,
Status VARCHAR(30),
FOREIGN KEY (Book_ID) REFERENCES Book_Details(Book_ID) ON DELETE CASCADE,
FOREIGN KEY (Customer_ID) REFERENCES Customer_Details(Customer_ID) ON DELETE CASCADE,
FOREIGN KEY (Employee_ID) REFERENCES Librarian_Details(Employee_ID) ON DELETE CASCADE
);